BeerPal/Controllers/SubscribersController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BeerPal.Models;
using BeerPal.Services.ServiceInterfaces;
using Microsoft.AspNet.Identity.Owin;
using PayPal.Api;

namespace BeerPal.Controllers
{
    public class SubscribersController : Controller
    {
        private ApplicationDbContext _dbContext => HttpContext.GetOwinContext().Get<ApplicationDbContext>();

        private readonly IPayPalApiHelperService PayPalApiHelperService;

        public SubscribersController(IPayPalApiHelperService payPalApiHelperService)
        {
            PayPalApiHelperService = payPalApiHelperService;
        }

        public ActionResult Index()
        {
            var subscriptions = _dbContext.Subscriptions.OrderByDescending(x => x.StartDate).Take(50).ToList();

            return View(subscriptions);
        }

        public ActionResult Details(string id)
        {
            var apiContext = PayPalApiHelperService.GetApiContext();

            var agreement = Agreement.Get(apiContext, id);

            return View(agreement);
        }

        public ActionResult Suspend(string id)
        {
            var apiContext = PayPalApiHelperService.GetApiContext();

            Agreement.Suspend(apiContext, id, new AgreementStateDescriptor()
            {
                note = "Suspended"
            });

            return RedirectToAction("Details", new {id = id});
        }

        public ActionResult Reactivate(string id)
        {
            var apiContext = PayPalApiHelperService.GetApiContext();

            Agreement.ReActivate(apiContext, id, new AgreementStateDescriptor()
            {
                note = "Reactivated"
            });

            return RedirectToAction("Details", new {id = id});
        }

        public ActionResult Cancel(string id)
        {
            var apiContext = PayPalApiHelperService.GetApiContext();

            Agreement.Cancel(apiContext, id, new AgreementStateDescriptor()
            {
                note = "Cancelled"
            });            

            return RedirectToAction("Details", new {id = id});
        }
    }
}

BeerPal/Views/Subscribers/Details.cshtml
@using Newtonsoft.Json
@model PayPal.Api.Agreement

@{
    ViewBag.Title = "Subscription Details";
}

<div class="heads" style="background: url(/public/img/brewery-back1.jpg) 50% 27%;">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2><span>//</span> Subscription Details</h2>
            </div>
        </div>
    </div>
</div>

<div class="page-content">
    <div class="container">
        <div class="row confirm">
            <div class="col-md-12">
                <a href="@Url.Action("Suspend", "Subscribers", new {id=Model.id})" @(Model.state != "Active" ? "disabled" : "") class="btn btn-warning">Suspend</a>
                <a href="@Url.Action("Reactivate", "Subscribers", new {id=Model.id})" @(Model.state != "Suspended" ? "disabled" : "") class="btn btn-warning">Re-activate</a>
                <a href="@Url.Action("Cancel", "Subscribers", new {id=Model.id})" @(Model.state != "Cancelled" ? "" : "disabled") class="btn btn-warning">Cancel</a>
            </div>
        </div>
        <div class="row confirm">
            <div class="col-md-12">
                <pre>@JsonConvert.SerializeObject(Model, Formatting.Indented)</pre>
            </div>
        </div>
    </div>
</div>

BeerPal/Views/Subscribers/Index.cshtml
@using BeerPal.Models.Subscription
@model List<BeerPal.Entities.Subscription>

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.Title = "Subscribers";
}

<div class="heads" style="background: url(/public/img/brewery-back1.jpg) 50% 27%;">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2><span>//</span> Subscribers</h2>
            </div>
        </div>
    </div>
</div>

<div class="page-content">
    <div class="container">
        <div class="row confirm">
            <div class="col-md-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Created Date</th>
                            <th>Plan</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.PayPalAgreementId</td>
                                <td>@item.StartDate</td>
                                <td>@(Plan.Plans.FirstOrDefault(x => x.PayPalPlanId == item.PayPalPlanId)?.Name ?? "[Deleted Plan]")</td>
                                <td class="text-right">
                                    <a href="@Url.Action("Details", "Subscribers" ,new {id=item.PayPalAgreementId})">View Details</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>